services:
  postgres:
    image: postgres:17
    container_name: employee-management-postgres

    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: